### PR TITLE
Fixes OAuth2 custom template bug

### LINKED ISSUE #1307: [Bug] Authorisation header not set properly when using OAuth2
## **Describe the bug**

When using OAuth2 authentication type the access_token is recovered fine but on subsequent requests the header contain BearerToken prefix instead of Bearer as specified in the documentation. 

We tried using authHeader and tokenTemplate fields to force it but it does not work when using authHeader = Authorization and/or tokenTemplate as the orginial Authorization header takes precedence (if we set a different authHeader it adds a second header with that name and if using on tokenTemplate our template gets ignored)

## **Steps to reproduce**

1. Create an infinity datasource with OAuth2 authentication

Image

2. Use datasoruce to query url

Image

**Note**: We intercepted the query with tcpdump and we can clearly see that the header is set too "Authorization: BearerToken *****************************"

Image

**Note2**: if setting the authHeader to Authorization2 (for example) than templating works and it create a second header with that name with the right value

## **Version Details:**

- Grafana version : 11.6.1
- Plugin version : 3.4.1

### PR DESCRIPTION
**Pull request by yesoreyeram**
Fixes #1307

### CODE REVIEW

**Review by itsmylife — APPROVED** [review]

File: pkg/httpclient/oauth2.go [hunk 1]
```diff
@@ -16,12 +17,21 @@ const (
...
 	Transport     http.RoundTripper
 	AuthHeader    string
 	TokenTemplate string
 	TokenSource   oauth2.TokenSource
 }
 
+func (t *oauth2CustomTokenTransport) Base(ctx context.Context) http.RoundTripper {
+	baseClient, err := getBaseHTTPClient(ctx, t.Settings)
+	if err != nil {
+		return http.DefaultTransport
```
Comment (zoltanbedi) [inline pkg/httpclient/oauth2.go]: We need to use the httpclient.NewHTTPTransport to avoid mutations. See

https://github.com/grafana/grafana-plugin-sdk-go/pull/1303

Comment (yesoreyeram) [reply pkg/httpclient/oauth2.go]: resolved in 492678103929e6bfaa55466e04690581be96ed87

**Review by zoltanbedi — APPROVED** [review]
lgtm
